import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const LANGUAGE_STORAGE_KEY = 'tryon_language'

const TRANSLATIONS = {
  en: {
    nav: {
      home: 'Home',
      tryOn: 'Try On',
      style: 'Style Explorer',
      login: 'Login',
      register: 'Register',
      profile: 'Profile',
      accountShortcuts: 'Account shortcuts',
      uploadAvatar: 'Upload avatar',
      removeImage: 'Remove image',
      avatarTooLarge: 'Please upload an image smaller than 1 MB for now.',
      logout: 'Logout',
      saved: 'Saved',
      savedLooks: 'Saved Looks',
      close: 'Close',
      loadingSaved: 'Loading saved items...',
      noSaved: 'No saved garments yet. Save a product from Style Explorer or Try On.',
      restoreToTryOn: 'Restore to Try On',
      remove: 'Remove',
      reviewHistory: 'Review History',
      purchaseHistory: 'Purchase History',
      tokenPurchase: 'Token Purchase',
      settings: 'Settings',
    },
    home: {
      eyebrow: 'Virtual Try-On · AI Fashion Agent',
      heroTitleLine1: 'See yourself',
      heroTitleLine2: 'in it.',
      heroBody: 'Describe your style, discover outfits curated just for you, and try them on your own photo before you buy.',
      tryItOn: 'Try It On',
      findMyStyle: 'Find My Style',
      whyTitle: 'Why it stands out',
      whyBody: 'Three capabilities that change how you shop for fashion online.',
      howTitle: 'How it works',
      ctaTitle: 'Your wardrobe, reimagined.',
      ctaBody: 'Start with a quick try-on or let the AI build your style profile.',
      quickTryOn: 'Quick Try-On',
      exploreMyStyle: 'Explore My Style',
    },
    auth: {
      createAccount: 'Create account',
      welcomeBack: 'Welcome back',
      register: 'Register',
      login: 'Login',
      registerBody: 'Create a profile now, and future memory features can build on it.',
      loginBody: 'Sign in to connect recommendations with your account.',
      username: 'Username',
      password: 'Password',
      authFailed: 'Authentication failed.',
      pleaseWait: 'Please wait...',
      createAccountCta: 'Create Account',
      loginCta: 'Login',
      alreadyHaveAccount: 'Already have an account?',
      newHere: 'New here?',
    },
    style: {
      title: 'Style Explorer',
      subtitle: "Tell us your aesthetic. We'll curate outfits made for you.",
      describeLabel: 'Describe your personal style',
      describePlaceholder: 'e.g. I love clean lines, neutral tones, and relaxed silhouettes that work from the office to dinner...',
      gender: 'Gender',
      aesthetic: 'Aesthetic',
      occasion: 'Occasion',
      referenceImages: 'Reference Images',
      optionalUpTo4: '(optional, up to 4)',
      loadingCatalog: 'Searching catalog...',
      analyze: 'Analyze My Style',
      selectGender: 'Select a Gender to Continue',
      styleConversation: 'Style Conversation',
      curateRefine: 'Curate and refine in chat',
      backForNewChat: 'Back for new chat',
      recommendationsUpdated: 'Recommendations updated.',
      styleDna: 'Style DNA',
      refinePlaceholder: 'Refine these results with a follow-up message...',
      send: 'Send',
      save: 'Save',
      tryOn: 'Try On',
      agentLoading: 'AI model loading... this takes about a minute on first run',
      agentTooLong: 'Agent took too long to load. Please refresh and try again.',
      unableUpdate: 'Unable to update recommendations right now.',
      networkError: 'Network error.',
      aiModelLoading: 'AI model loading...',
    },
    tryOn: {
      title: 'Virtual Try-On',
      subtitle: 'Upload or paste your photo and a garment image to see how it looks on you.',
      yourPhoto: 'Your Photo',
      garmentImage: 'Garment Image',
      selectedItem: 'Selected item',
      garmentType: 'Garment Type',
      styleNote: 'Style Note',
      optional: '(optional)',
      stylePlaceholder: 'casual, office, streetwear...',
      processing: 'Processing...',
      tryOn: 'Try On',
      generating: 'Generating your try-on...',
      takesTime: 'This takes about 20-40 seconds',
      resultHere: 'Your try-on result will appear here',
      saveGarment: 'Save Garment',
      openFullSize: 'Open Full Size',
      savedGarmentFallback: 'Saved garment',
    },
    review: {
      eyebrow: 'Review History',
      title: 'Every search in this session',
      body: 'This page keeps the recommendation batches from your current signed-in session. Logging out clears this working review trail after its summary is flushed into long-term memory.',
      refresh: 'Refresh session history',
      loading: 'Loading review history...',
      empty: 'No recommendation batches have been generated in this session yet.',
      noGrid: 'This turn did not store a recommendation grid.',
      sendToTryOn: 'Send to Try On',
      unableLoad: 'Unable to load review history.',
    },
    settings: {
      eyebrow: 'Settings',
      title: 'Long-term style summary',
      body: 'This summary is generated from your long-term memory records, so it persists beyond a single session and reflects the preferences the system has retained about your style.',
      loading: 'Generating your style summary...',
      persistentProfile: 'Persistent Memory Profile',
      memoryEntries: 'memory entries',
      empty: 'No long-term style summary is available yet. After more sessions are flushed into memory, this page will start to reflect your stable style preferences.',
      confidence: 'confidence',
      unableLoad: 'Unable to load style summary.',
    },
    account: {
      purchaseEyebrow: 'Purchase History',
      purchaseTitle: 'Your future purchase archive',
      purchaseDescription: 'Orders, reorder paths, and style follow-ups can live here once checkout and product ownership are connected.',
      tokensEyebrow: 'Token Purchase',
      tokensTitle: 'Credits and usage will land here',
      tokensDescription: 'This page is ready for try-on credits, premium memory tiers, and any future balance or billing controls.',
      settingsEyebrow: 'Settings',
      settingsTitle: 'A clean home for account controls',
      settingsDescription: 'Profile controls, avatar preferences, notification settings, and memory permissions can expand here later.',
      experiencePlaceholder: 'Experience placeholder',
      experienceBody: 'The route, layout, and visual language are in place now, so we can plug in real account data next without rebuilding the page structure.',
      backendHook: 'Next backend hook',
      backendHookBody: 'When you are ready, this section can connect directly to the matching API endpoints and database tables for the selected account feature.',
    },
    features: {
      feature1Title: 'AI-Powered Style Matching',
      feature1Body: "Describe your aesthetic in plain words. Our LLM extracts your latent taste profile and surfaces clothes you'll actually love.",
      feature2Title: 'Realistic Virtual Try-On',
      feature2Body: "See any garment on your own photo before you buy, powered by FASHN's state-of-the-art diffusion model.",
      feature3Title: 'Conversational Shopping',
      feature3Body: 'Refine your search in natural language. Our agent understands follow-ups like "something more casual" or "for a rooftop dinner".',
    },
    steps: {
      describe: 'Describe',
      describeBody: 'Tell us your style in words or show us reference images.',
      discover: 'Discover',
      discoverBody: 'The agent surfaces outfit candidates ranked to your taste.',
      visualize: 'Visualize',
      visualizeBody: 'Try any piece on your own photo instantly.',
      decide: 'Decide',
      decideBody: "Shop with confidence. No more guessing how it'll look on you.",
    },
  },
  zh: {
    nav: {
      home: '首页',
      tryOn: '试穿',
      style: '风格探索',
      login: '登录',
      register: '注册',
      profile: '个人主页',
      accountShortcuts: '账户快捷入口',
      uploadAvatar: '上传头像',
      removeImage: '移除图片',
      avatarTooLarge: '请上传小于 1 MB 的图片。',
      logout: '退出登录',
      saved: '收藏',
      savedLooks: '已收藏单品',
      close: '关闭',
      loadingSaved: '正在加载收藏...',
      noSaved: '还没有收藏的单品。可以先从风格探索或试穿页面保存。',
      restoreToTryOn: '恢复到试穿页',
      remove: '移除',
      reviewHistory: '回顾历史',
      purchaseHistory: '购买历史',
      tokenPurchase: '额度购买',
      settings: '设置',
    },
    home: {
      eyebrow: '虚拟试穿 · AI 时尚助手',
      heroTitleLine1: '先看看自己',
      heroTitleLine2: '穿上它的样子。',
      heroBody: '描述你的风格，发现为你定制的穿搭推荐，再把它们试穿到自己的照片上。',
      tryItOn: '开始试穿',
      findMyStyle: '寻找我的风格',
      whyTitle: '它为什么特别',
      whyBody: '三种能力一起改变你在线挑选服装的方式。',
      howTitle: '使用流程',
      ctaTitle: '重新想象你的衣橱。',
      ctaBody: '可以先快速试穿，也可以先让 AI 帮你建立风格画像。',
      quickTryOn: '快速试穿',
      exploreMyStyle: '探索我的风格',
    },
    auth: {
      createAccount: '创建账户',
      welcomeBack: '欢迎回来',
      register: '注册',
      login: '登录',
      registerBody: '先创建账户，后续的长期记忆和个性化能力都可以建立在这个账户上。',
      loginBody: '登录后，推荐结果和你的账户会关联起来。',
      username: '用户名',
      password: '密码',
      authFailed: '认证失败。',
      pleaseWait: '请稍等...',
      createAccountCta: '创建账户',
      loginCta: '登录',
      alreadyHaveAccount: '已经有账户了？',
      newHere: '第一次来？',
    },
    style: {
      title: '风格探索',
      subtitle: '告诉我们你的审美偏好，我们会为你策划推荐。',
      describeLabel: '描述你的个人风格',
      describePlaceholder: '例如：我喜欢利落线条、中性色调，以及适合从办公室到晚餐场合的宽松剪裁...',
      gender: '性别偏好',
      aesthetic: '审美风格',
      occasion: '场景',
      referenceImages: '参考图片',
      optionalUpTo4: '（可选，最多 4 张）',
      loadingCatalog: '正在搜索商品库...',
      analyze: '分析我的风格',
      selectGender: '请先选择性别偏好',
      styleConversation: '风格对话',
      curateRefine: '在对话里继续细化推荐',
      backForNewChat: '返回重新开始',
      recommendationsUpdated: '推荐结果已更新。',
      styleDna: '风格 DNA',
      refinePlaceholder: '继续输入你的新要求来微调推荐...',
      send: '发送',
      save: '收藏',
      tryOn: '试穿',
      agentLoading: 'AI 模型正在加载，首次启动大约需要一分钟',
      agentTooLong: '模型启动时间过长，请刷新后再试。',
      unableUpdate: '暂时无法更新推荐结果。',
      networkError: '网络请求失败。',
      aiModelLoading: 'AI 模型加载中...',
    },
    tryOn: {
      title: '虚拟试穿',
      subtitle: '上传或粘贴你的照片和服装图片，看看穿在你身上的效果。',
      yourPhoto: '你的照片',
      garmentImage: '服装图片',
      selectedItem: '当前选择',
      garmentType: '服装类型',
      styleNote: '风格备注',
      optional: '（可选）',
      stylePlaceholder: '例如：休闲、通勤、街头风...',
      processing: '处理中...',
      tryOn: '开始试穿',
      generating: '正在生成试穿效果...',
      takesTime: '大约需要 20-40 秒',
      resultHere: '试穿结果会显示在这里',
      saveGarment: '收藏单品',
      openFullSize: '查看原图',
      savedGarmentFallback: '已收藏单品',
    },
    review: {
      eyebrow: '回顾历史',
      title: '本次会话中的每次搜索',
      body: '这里会保留你当前登录会话中的推荐批次。退出登录后，这段工作历史会在总结写入长期记忆后被清空。',
      refresh: '刷新当前会话历史',
      loading: '正在加载回顾历史...',
      empty: '本次会话里还没有生成推荐批次。',
      noGrid: '这一轮没有保存推荐卡片。',
      sendToTryOn: '送到试穿页',
      unableLoad: '无法加载回顾历史。',
    },
    settings: {
      eyebrow: '设置',
      title: '长期风格总结',
      body: '这份总结来自你的长期记忆记录，因此不会随着单次会话结束而消失，反映的是系统目前保留下来的稳定风格偏好。',
      loading: '正在生成你的风格总结...',
      persistentProfile: '持久化记忆画像',
      memoryEntries: '条记忆',
      empty: '目前还没有可展示的长期风格总结。随着更多会话写入长期记忆，这里会逐渐形成更稳定的偏好画像。',
      confidence: '置信度',
      unableLoad: '无法加载风格总结。',
    },
    account: {
      purchaseEyebrow: '购买历史',
      purchaseTitle: '未来的购买档案页',
      purchaseDescription: '等到结账和商品归属链路接上以后，订单、复购路径和购买后的风格跟进都可以放在这里。',
      tokensEyebrow: '额度购买',
      tokensTitle: '额度和使用记录会放在这里',
      tokensDescription: '这个页面已经为试穿额度、高级记忆层级，以及后续余额和计费控制预留好了位置。',
      settingsEyebrow: '设置',
      settingsTitle: '一个干净的账户控制页',
      settingsDescription: '后续这里可以逐步扩展用户资料、头像偏好、通知设置和记忆权限等控制项。',
      experiencePlaceholder: '页面占位',
      experienceBody: '当前路由、布局和视觉风格已经搭好，后续可以直接接真实账户数据，而不需要重做页面结构。',
      backendHook: '下一步后端接入',
      backendHookBody: '当你准备好了，这一页可以直接连接对应的 API 接口和数据库表。',
    },
    features: {
      feature1Title: 'AI 驱动的风格匹配',
      feature1Body: '你只需要自然地描述喜欢的感觉，系统会提取潜在偏好，并给出更贴近你审美的服装。',
      feature2Title: '更真实的虚拟试穿',
      feature2Body: '在购买前，先把任意单品试穿到自己的照片上，底层由 FASHN 的扩散模型驱动。',
      feature3Title: '对话式购物',
      feature3Body: '你可以继续用自然语言微调推荐，像“更休闲一点”或“适合露台晚餐”这样的要求都能理解。',
    },
    steps: {
      describe: '描述',
      describeBody: '用文字说出你的风格，或者上传参考图片。',
      discover: '发现',
      discoverBody: '系统会按你的偏好排序出合适的候选穿搭。',
      visualize: '可视化',
      visualizeBody: '把任意单品立刻试穿到你自己的照片上。',
      decide: '决定',
      decideBody: '更有把握地购物，不再只能靠想象判断上身效果。',
    },
  },
}

const OPTION_LABELS = {
  gender: {
    Women: { en: 'Women', zh: '女装' },
    Men: { en: 'Men', zh: '男装' },
    Unisex: { en: 'Unisex', zh: '中性' },
  },
  aesthetic: {
    Minimalist: { en: 'Minimalist', zh: '极简' },
    Streetwear: { en: 'Streetwear', zh: '街头' },
    Bohemian: { en: 'Bohemian', zh: '波西米亚' },
    Preppy: { en: 'Preppy', zh: '学院' },
    'Dark Academia': { en: 'Dark Academia', zh: '暗黑学院' },
    Y2K: { en: 'Y2K', zh: '千禧风' },
    Coastal: { en: 'Coastal', zh: '海岸感' },
    'Office-Core': { en: 'Office-Core', zh: '通勤风' },
    Cottagecore: { en: 'Cottagecore', zh: '田园风' },
    Romantic: { en: 'Romantic', zh: '浪漫' },
    Edgy: { en: 'Edgy', zh: '个性前卫' },
  },
  occasion: {
    Everyday: { en: 'Everyday', zh: '日常' },
    Work: { en: 'Work', zh: '工作' },
    'Date Night': { en: 'Date Night', zh: '约会夜' },
    Weekend: { en: 'Weekend', zh: '周末' },
    Formal: { en: 'Formal', zh: '正式' },
    Beach: { en: 'Beach', zh: '海边' },
    Party: { en: 'Party', zh: '派对' },
  },
  garmentType: {
    top: { en: 'Top', zh: '上装' },
    jacket: { en: 'Jacket', zh: '夹克' },
    coat: { en: 'Coat', zh: '外套' },
    dress: { en: 'Dress', zh: '连衣裙' },
    pants: { en: 'Pants', zh: '裤装' },
    skirt: { en: 'Skirt', zh: '裙装' },
    shorts: { en: 'Shorts', zh: '短裤' },
  },
}

const LanguageContext = createContext(null)

function getByPath(object, path) {
  return path.split('.').reduce((current, key) => current?.[key], object)
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY)
    return stored === 'zh' ? 'zh' : 'en'
  })

  useEffect(() => {
    localStorage.setItem(LANGUAGE_STORAGE_KEY, language)
  }, [language])

  const value = useMemo(() => ({
    language,
    setLanguage,
    toggleLanguage: () => setLanguage((current) => (current === 'en' ? 'zh' : 'en')),
    t: (path, fallback = path) => getByPath(TRANSLATIONS[language], path) ?? fallback,
    optionLabel: (group, value) => OPTION_LABELS[group]?.[value]?.[language] ?? value,
    isChinese: language === 'zh',
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
